title: Thuong Nguyen's Blog
email: thuuongnguyen.net@gmail.com
description: >
  ...
baseurl: ""
url: "https://thuongnguyen.me"
twitter_username: hthuong09
github_username:  hthuong09


permalink: /blog/:categories/:title/

paginate_path: /blog/page/:num/
paginate: 5

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
