title: Thuong Nguyen Blog
email: thuongnguyen.net@gmail.com
description: Just another software developer's blog
baseurl: ""
url: "https://thuongnguyen.me"

# Social links
github_username:  hthuong09
linkedin_username: hthuong09
stackoverflow_userid: 1414360
facebook_username: hthuong09
twitter_username: hthuong09



permalink: /blog/:categories/:title/

paginate_path: /blog/page/:num/
paginate: 5

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
